runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bootstrap
  static_dir: bootstrap
  
- url: .*
  script: main.app
  

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest